name: R Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.4.0'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages("testthat")'

    - name: Run tests
      run: |
        Rscript -e 'testthat::test_dir("test", stop_on_failure = TRUE)'
