# Function to log input, output, and rules into a JSON file
# 
# Args:
#   input: Input data or parameters
#   output: Output data or results
#   rules: Rules generated by the model
# 
# Returns:
#   None
# 
log <- function(input, output, rules) {
  # Combine input, output, and rules into a list with current timestamp
  combined_list <- list(time = Sys.time(), input = input, output = output, rules = rules)
  
  # Convert the combined list to JSON format
  new_json_string <- toJSON(combined_list)
  
  # Check if the file exists
  if (file.exists("log.json")) {
    # Read existing JSON data
    existing_data <- paste(readLines("log.json"), collapse = "")
    # Remove the closing bracket "]" if it exists
    if (endsWith(existing_data, "]")) {
      existing_data <- substr(existing_data, 1, nchar(existing_data) - 1)
    }
    # Append a comma before writing the new JSON data
    write(paste0(existing_data, ",", new_json_string, "]"), "log.json")
  } else {
    # Create a new file and write the JSON array
    write(paste0("[", new_json_string, "]"), "log.json")
  }
  
}



