
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(caret))
suppressPackageStartupMessages(library(arulesCBA))
suppressPackageStartupMessages(library(jsonlite))
suppressPackageStartupMessages(library(lubridate))
source("modules/log.R")
source("modules/model.R")
source("modules/report.R")
source("modules/warnings.R")

#### Asignación de la semilla

set.seed(123)

# Function to initialize a model by reading data, splitting it, and creating a classification model
# 
# Args:
#   data: File path of the filtered data
#   support: Minimum support threshold for CARs
#   confidence: Minimum confidence threshold for CARs
# 
# Returns:
#   A list containing transactions, rules, weights, and a sample from the testing set
# 
init_model <- function(data, support, confidence) {

  warnings("Beware that you are using an AI model and that human supervision is necessary to make decisions.")

  #### Read filtered file
  data <- read.csv(data, header = TRUE, sep = ",")
  
  data <- mutate_all(data, as.factor)

  #### Create the model
  model <- create_model(data, support, confidence, data$weights)

  # Return a list containing transactions, rules, weights, and a sample from the testing set
  list(transactions = model$transactions, rules = model$rules, weights = data$weights)
}


# Function to predict using a classification model based on association rules
# 
# Args:
#   transactions: Transactions used to train the model
#   rules: Rules generated by the model
#   weights: Weights associated with the transactions
#   to_predict: New data to make predictions on
#   get_rules: Whether to return the rules used for prediction (default is FALSE)
# 
# Returns:
#   A list containing predictions and optionally the rules used for prediction
# 
predict_model <- function(transactions, rules, weights, to_predict, get_rules = FALSE) {
  # Fit the model with weights and the rules
  classifier <- CBA_ruleset(Class ~ .,
                            rules = rules,
                            default = uncoveredMajorityClass(Class ~ ., transactions, rules),
                            method = "majority",
                            weights = weights)

  # Convert data to transactions
  trans_predict <- as(to_predict, "transactions")

  # Make predictions
  prediction <- predict(classifier, trans_predict)

  # Get rules used for prediction
  rules_used <- get_used_rules(classifier, to_predict)

  # Log input, output, and rules
  log(to_predict, prediction, rules_used)

  # Conditionally return rules
  if (!get_rules) {
    rules_used <- NULL
  }

  # Return predictions and optionally rules used for prediction
  list(prediction = prediction, rules = rules_used)
}

if (!interactive()) {
  
    # Initializing with provided parameters
    model <- init_model("../data/Statlog_rCBA.csv", 0.7, 0.01, 0.01)
    # Creating dataframe
    df <- data.frame(
      'Status.of.existing.checking.account' = c('< 0 DM'),
      'Duration.in.month' = c('(3~12]'),
      'Credit.history' = c('critical account'),
      'Purpose' = c('radio/television'),
      'Credit.amount' = c('(249~1.26e+03]'),
      'Savings.account.bonds' = c('unknown/no savings'),
      'Present.employment.since' = c('>= 7 years'),
      'Installment.rate.in.percentage.of.disposable.income' = c('(3~4]'),
      'Other.debtors...guarantors' = c('none'),
      'Present.residence.since' = c('(2~4]'),
      'Age.in.years' = c('(45~75]'),
      'Other.installment.plans' = c('none'),
      'Housing' = c('own'),
      'Number.of.existing.credits.at.this.bank' = c('(0~2]'),
      'Job' = c('skilled employee'),
      'Number.of.people.being.liable.to.provide.maintenance.for' = c('(0~2]'),
      'Telephone' = c('yes~ registered'),
      'Foreign.worker' = c('yes'),
      'Gender' = c('male'),
      'Marital.Status' = c('single')
    )
    # Predicting
    p <- predict_model(model$transactions, model$rules, model$weights, df, TRUE)
    print(p$prediction)
}