library(tidyverse)
library(caret)
library(arulesCBA)
library(jsonlite)
source("utils.R")

#### Asignación de la semilla

set.seed(123)

# Function to initialize a model by reading data, splitting it, and creating a classification model
# 
# Args:
#   data: File path of the filtered data
#   split_ratio: Ratio to split the data into training and testing sets
#   support: Minimum support threshold for CARs
#   confidence: Minimum confidence threshold for CARs
# 
# Returns:
#   A list containing transactions, rules, weights, and a sample from the testing set
# 
init_model <- function(data, split_ratio, support, confidence) {
  #### Read filtered file
  data <- read.csv(data, header = TRUE, sep = ",")

  #### Process the data
  data <- train_test_weights_split(data, split_ratio)

  #### Create the model
  model <- create_model(data$train, support, confidence, data$weights)

  # Return a list containing transactions, rules, weights, and a sample from the testing set
  list(transactions = model$transactions, rules = model$rules, weights = data$weights, test_sample = data$test[1, ])
}


# Function to predict using a classification model based on association rules
# 
# Args:
#   transactions: Transactions used to train the model
#   rules: Rules generated by the model
#   weights: Weights associated with the transactions
#   to_predict: New data to make predictions on
#   get_rules: Whether to return the rules used for prediction (default is FALSE)
# 
# Returns:
#   A list containing predictions and optionally the rules used for prediction
# 
predict_model <- function(transactions, rules, weights, to_predict, get_rules = FALSE) {
  # Fit the model with weights and the rules
  classifier <- CBA_ruleset(Class ~ .,
                            rules = rules,
                            default = uncoveredMajorityClass(Class ~ ., transactions, rules),
                            method = "majority",
                            weights = weights)

  # Convert data to transactions
  trans_predict <- as(to_predict, "transactions")

  # Make predictions
  prediction <- predict(classifier, trans_predict)

  # Get rules used for prediction
  rules_used <- get_used_rules(classifier, to_predict)

  # Log input, output, and rules
  log(to_predict, prediction, rules_used)

  # Conditionally return rules
  if (!get_rules) {
    rules_used <- NULL
  }

  # Return predictions and optionally rules used for prediction
  list(prediction = prediction, rules = rules_used)
}

